// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkgkxchlgzffcdvhzeqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrZ2t4Y2hsZ3pmZmNkdmh6ZXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzM4MTcsImV4cCI6MjA2NTg0OTgxN30.U5fyrdzsxXO63xUJMYdJxaF0mi8uVZmZ6GIjUgC4XAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);